GET http://localhost:3001/api/ingredients

###

GET http://localhost:3001/api/ingredients/<id>



###
POST http://localhost:3001/api/ingredients/
Content-Type: application/json

{
    "name": "test",
}


###

DELETE http://localhost:3001/api/ingredients/68c2f8ba974db70028f2b4ed

###
DELETE http://localhost:3001/api/ingredients/