GET http://localhost:3001/api/ingredients


### ingredient create expects fields:
# name, portionCost, portions, expiryDate

POST http://localhost:3001/api/ingredients/
Content-Type: application/json

{
    "name": "test",
    "portionCost": 100,
    "portions": 2,
    "expiryDate": "10-10-2026"
}


###

DELETE http://localhost:3001/api/ingredients/