## "username": "root",
## "password": "Password123!",


GET http://localhost:3001/api/users/testing

###  create user
POST http://localhost:3001/api/users/register
content-type: application/json

{
    "username": "root",
    "password": "Password123!"
}


### not an actual endpoint, just a quick delete for testing
DELETE http://localhost:3001/api/users/deleteForTesting/68b5ec7e8647abc722e18218


###
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "username": "root",
    "password": "Password123!"
}


### 

POST http://localhost:3001/api/users/logout
Content-Type: application/json

{
    "username": "root",
    "password": "Password123!"
}

### updatepw requires username, password, newPassword

PUT http://localhost:3001/api/users/updatePw
Content-Type: application/json

{
    "username": "root",
    "password": "Password123!",
    "newPassword": "Password123!"
}

###
DELETE http://localhost:3001/api/users/deleteAccount
Content-Type: application/json

{
    "username": "test2",
    "password": "pw"
}

### update username/recipeList/stock 

PUT http://localhost:3001/api/users/updateUser
Content-Type: application/json

{
    "username": "test2",
    "password": "pw"
}