## "username": "root",
## "password": "password",
## "bypassPwRequirements": true
## token is: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGI1ZWM3ZTg2NDdhYmM3MjJlMTgyMTgiLCJ1c2VybmFtZSI6InJvb3QiLCJpYXQiOjE3NTY3NTgwMzEsImV4cCI6MTc1NzM2MjgzMX0.PYNDObdAclPP1FPislIpXLMPANxx4G-97z7GeLjV7bc
##token expires sept 8


GET http://localhost:3001/api/users/testing

###  create user
POST http://localhost:3001/api/users/register
content-type: application/json

{
    "username": "root",
    "password": "password",
    "bypassPwRequirements": true
}


### not an actual endpoint, just a quick delete for testing
DELETE http://localhost:3001/api/users/deleteForTesting/68b4bc410cbeb8fd4100c5d9


###
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "username": "root",
    "password": "password",
    "bypassPwRequirements": true
}

### updatepw requires username, password, newPassword

PUT http://localhost:3001/api/users/updatePw
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGI0YmQ2OTM3YWU0NTRjMWVhOTZlMmMiLCJ1c2VybmFtZSI6InJvb3QyIiwiaWF0IjoxNzU2NzU0OTcxLCJleHAiOjE3NTczNTk3NzF9.Mc1B5J2SjLq1goVKz4BfEN31-qjlRyN2y19i6S4JTWs

{
    "username": "root2",
    "password": "password2",
    "bypassPwRequirements": true,
    "newPassword": "password"
}

### token for user to delete: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGI0YmQ2OTM3YWU0NTRjMWVhOTZlMmMiLCJ1c2VybmFtZSI6InJvb3QyIiwiaWF0IjoxNzU2NzU1MDYwLCJleHAiOjE3NTczNTk4NjB9.UAf2jsZ3wz7qVFIfYTD-lCTJl8L6k8FF0aQHxtgTu_A
DELETE http://localhost:3001/api/users/deleteAccount
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGI0YmQ2OTM3YWU0NTRjMWVhOTZlMmMiLCJ1c2VybmFtZSI6InJvb3QyIiwiaWF0IjoxNzU2NzU1MDYwLCJleHAiOjE3NTczNTk4NjB9.UAf2jsZ3wz7qVFIfYTD-lCTJl8L6k8FF0aQHxtgTu_A

{
    "username": "root2",
    "password": "password2",
    "bypassPwRequirements": true
}

### update username/recipeList/stock 

PUT http://localhost:3001/api/users/updateUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGI1ZWM3ZTg2NDdhYmM3MjJlMTgyMTgiLCJ1c2VybmFtZSI6InJvb3QiLCJpYXQiOjE3NTY3NTgwMzEsImV4cCI6MTc1NzM2MjgzMX0.PYNDObdAclPP1FPislIpXLMPANxx4G-97z7GeLjV7bc

{
    "username": "root",
    "password": "password",
    "bypassPwRequirements": true
}